CREATE TABLE if not exists recipe_likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    recipe_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    PRIMARY KEY (recipe_id, user_id),
    FOREIGN KEY(recipe_id) REFERENCES recipe(id),
    FOREIGN KEY(user_id) REFERENCES rs_user(id)
);
